#!/usr/bin/env bash
set -euo pipefail

dry_run=0

if [[ "${1:-}" == "--dry-run" ]]; then
    dry_run=1
    shift
fi

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 [--dry-run] SYSTEM-COORDINATES.pdb" >&2
    exit 2
fi

die() {
    echo "Error: $*" >&2
    exit 1
}

# Inputs and user settings
coordinate_pdb=$1
tleap=${TLEAP:-tleap}
python=${PYTHON:-python3}

work_dir=${WORK_DIR:-work}
amber_named_pdb="$work_dir/amber-named.pdb"
generated_tleap="$work_dir/tleap.in"

# Input and dependency checks
if (( ! dry_run )); then
    if [[ ! -f "$coordinate_pdb" ]]; then
        die "coordinate PDB not found: $coordinate_pdb"
    fi

    if ! command -v "$tleap" >/dev/null 2>&1; then
        die "tleap not found: $tleap"
    fi
    if ! command -v "$python" >/dev/null 2>&1; then
        die "Python executable not found: $python"
    fi
fi

# Dry run prints commands without creating files.
if (( dry_run )); then
    printf 'mkdir -p %q\n' "$work_dir"
    printf 'cp %q %q\n' "$coordinate_pdb" "$amber_named_pdb"
    printf '%q %q %q %q %q\n' \
        "$python" \
        prepare_tleap.py \
        "$amber_named_pdb" \
        tleap.in \
        "$generated_tleap"
    printf 'cd %q\n' "$work_dir"
    printf '%q \\\n' "$tleap"
    printf '  -f tleap.in\n'
    exit 0
fi

echo "Generating the AMBER topology (ff19SB/Lipid21/OPC)."
mkdir -p "$work_dir"

# Preserve the AMBER/Lipid21 naming generated by the coordinate build.
cp "$coordinate_pdb" "$amber_named_pdb"

if [[ ! -s "$amber_named_pdb" ]]; then
    die "Could not prepare the tleap input PDB: $amber_named_pdb"
fi

"$python" \
    prepare_tleap.py \
    "$amber_named_pdb" \
    tleap.in \
    "$generated_tleap"

# Apply ff19SB, Lipid21, and OPC to the converted coordinate file.
if ! (
    cd "$work_dir"
    "$tleap" \
        -f tleap.in \
        > leap.log 2>&1
); then
    die "tleap failed. See log: $work_dir/leap.log"
fi

if [[ ! -s "$work_dir/system.parm7" ]]; then
    die "Topology was not created. See log: $work_dir/leap.log"
fi

if [[ ! -s "$work_dir/system.rst7" ]]; then
    die "Restart file was not created. See log: $work_dir/leap.log"
fi

echo "AMBER topology and restart: $work_dir"
