#!/usr/bin/env bash
set -euo pipefail

dry_run=0
if [[ "${1:-}" == "--dry-run" ]]; then
    dry_run=1
    shift
fi
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 [--dry-run] SYSTEM-COORDINATES.pdb" >&2
    exit 2
fi

die() {
    echo "Error: $*" >&2
    exit 1
}

coordinate_pdb=$1
work_dir=work
amber_named_pdb="$work_dir/amber-named.pdb"
generated_tleap="$work_dir/tleap.in"

if [[ ! -f "$coordinate_pdb" ]]; then
    die "Coordinate PDB not found: $coordinate_pdb"
fi
if (( ! dry_run )) && ! command -v tleap >/dev/null 2>&1; then
    die "tleap not found."
fi
if (( ! dry_run )) && ! command -v python3 >/dev/null 2>&1; then
    die "python3 not found."
fi
if (( ! dry_run )) && find "$work_dir" -type f \
    \( -name 'min*.out' -o -name 'heat*.out' -o -name 'equil*.out' \
       -o -name 'production*.out' \) -print -quit 2>/dev/null | grep -q .; then
    die "Simulation output already exists in $work_dir. Remove it before rebuilding."
fi

if (( dry_run )); then
    printf '+ cp %q %q\n' "$coordinate_pdb" "$amber_named_pdb"
    printf '+ python3 prepare_tleap.py %q %q %q\n' "$amber_named_pdb" tleap.in "$generated_tleap"
    printf '+ (cd %q && tleap -f tleap.in)\n' "$work_dir"
    exit 0
fi

echo "Generating the AMBER topology (ff19SB/Lipid21/OPC)."
mkdir -p "$work_dir"

# Preserve the AMBER/Lipid21 naming generated by the coordinate build.
cp "$coordinate_pdb" "$amber_named_pdb"

if [[ ! -s "$amber_named_pdb" ]]; then
    die "Could not prepare the tleap input PDB: $amber_named_pdb"
fi

python3 \
    prepare_tleap.py \
    "$amber_named_pdb" \
    tleap.in \
    "$generated_tleap"

# Apply ff19SB, Lipid21, and OPC to the converted coordinate file.
if ! (
    cd "$work_dir"
    tleap \
        -f tleap.in \
        > leap.log 2>&1
); then
    die "tleap failed. See log: $work_dir/leap.log"
fi

if [[ ! -s "$work_dir/system.parm7" ]]; then
    die "Topology was not created. See log: $work_dir/leap.log"
fi

if [[ ! -s "$work_dir/system.rst7" ]]; then
    die "Restart file was not created. See log: $work_dir/leap.log"
fi

echo "AMBER topology and restart: $work_dir"
